### ISSUE TITLE
Main.py dont run

### ISSUE THREAD

**Issue by DavideM78** [kurobeats/wordhound#1]
Hi everybody, 
I'm just since yesterday trying to install wordhound on Kali but it doesn't work.
Here is what I get:

root@kali:/opt/wordhound# python2.7 Main.py                
Traceback (most recent call last):
File "Main.py", line 5, in <module>                                    
import client as cli
File "/opt/wordhound/client.py", line 8, in <module>                   
import crawler
File "/opt/wordhound/crawler.py", line 17, in <module>                 
import bs4
File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30,
in <module>
from .builder import builder_registry, ParserRejectedMarkup          
File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", l
line 311, in <module>
from . import _html5lib
File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py",
line 57, in <module>
class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

Any suggestion would be very appreciate.
Best, 
Davide

**Comment by DavideM78** [comment]
I fixed by running:
pip install --upgrade html5lib==1.0b8
